# tools.py
import os
import json
import requests
import ollama
from datetime import datetime
from pathlib import Path
from bs4 import BeautifulSoup
from typing import List, Dict, Any, Optional
from config import config
import logging
from prompts import (structure_prompt as structure_prompt_template,)

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class LearningGuideTools:
    def __init__(self):
        try:
            self.ollama_client = ollama.Client(host=config.ollama_base_url)
            # Test connection
            self.ollama_client.list()
            logger.info("Successfully connected to Ollama")
        except Exception as e:
            logger.error(f"Failed to connect to Ollama: {e}")
            raise

    def prompt_selector_tool(self, user_query: str) -> str:
        """Analyze user query and return appropriate prompt template"""
        query_lower = user_query.lower()

        beginner_keywords = [
            "beginner",
            "basics",
            "intro",
            "getting started",
            "basic",
            "simple",
        ]
        advanced_keywords = [
            "advanced",
            "expert",
            "professional",
            "deep dive",
            "complex",
        ]
        complete_keywords = [
            "zero to advance",
            "complete",
            "comprehensive",
            "full",
            "end to end",
        ]

        if any(term in query_lower for term in complete_keywords):
            return "complete"
        elif any(term in query_lower for term in advanced_keywords):
            return "advanced"
        elif any(term in query_lower for term in beginner_keywords):
            return "beginner"
        else:
            return "complete"  # Default to complete

    def create_folder_tool(self, topic: str) -> str:
        """Create unique folder with timestamp for the learning guide"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_topic = "".join(
                c for c in topic if c.isalnum() or c in (" ", "-", "_")
            ).rstrip()
            safe_topic = safe_topic.replace(" ", "_")[:50]  # Limit length
            folder_name = f"{safe_topic}_{timestamp}"

            folder_path = Path(config.output_dir) / folder_name
            folder_path.mkdir(parents=True, exist_ok=True)

            logger.info(f"Created folder: {folder_path}")
            return str(folder_path)
        except Exception as e:
            logger.error(f"Error creating folder: {e}")
            raise

    def create_index_file_tool(
        self, folder_path: str, topic: str, topics_list: List[Dict]
    ) -> str:
        """Create index.md file with Hugo front matter and TOC"""
        try:
            current_date = datetime.now().strftime("%Y-%m-%dT%H:%M:%S+00:00")

            front_matter = f"""---
title: "{topic} - Complete Learning Guide"
date: {current_date}
draft: false
tags: ["{topic.lower()}", "index", "learning-path"]
categories: ["Learning Guides"]
toc: false
type: "guide-index"
description: "Comprehensive learning guide for {topic} from beginner to advanced"
weight: 1
---

# {topic} - Complete Learning Guide

Welcome to the comprehensive {topic} learning guide! This guide is structured to take you from beginner concepts to advanced implementations.

## 📚 Table of Contents

"""

            # Add links to each chapter
            for i, topic_item in enumerate(topics_list, 1):
                chapter_title = topic_item["title"]
                filename = self._create_filename(chapter_title)
                front_matter += f"{i}. [{chapter_title}](./{filename})\n"

                # Add subtopics if they exist
                if "subtopics" in topic_item and topic_item["subtopics"]:
                    for subtopic in topic_item["subtopics"]:
                        front_matter += f"   - {subtopic}\n"
                    front_matter += "\n"

            front_matter += f"""
## 🎯 How to Use This Guide

1. **Start with the Index** - You're here! This gives you an overview of all topics
2. **Follow the Sequential Order** - Each chapter builds upon the previous ones
3. **Practice Along** - Every chapter includes practical examples and exercises
4. **Take Your Time** - Don't rush; understanding is more important than speed

## 🔥 What You'll Learn

By completing this guide, you'll have a solid understanding of {topic} from fundamental concepts to advanced implementations, ready to apply your knowledge in real-world projects.

## 📊 Progress Tracking

- Total Chapters: {len(topics_list)}
- Estimated Time: {len(topics_list) * 2} hours
- Difficulty: Progressive (Beginner → Advanced)

---

*Generated by AI Learning Guide Generator on {datetime.now().strftime("%Y-%m-%d")}*
"""

            index_path = Path(folder_path) / "index.md"
            with open(index_path, "w", encoding="utf-8") as f:
                f.write(front_matter)

            logger.info(f"Created index file: {index_path}")
            return str(index_path)
        except Exception as e:
            logger.error(f"Error creating index file: {e}")
            raise

    def create_chapter_files_tool(
        self, folder_path: str, chapters: List[Dict]
    ) -> Dict[str, str]:
        """Create empty markdown files for each main chapter"""
        try:
            chapter_files = {}

            for i, chapter in enumerate(chapters, 1):
                chapter_title = chapter["title"]
                filename = self._create_filename(chapter_title)
                file_path = Path(folder_path) / filename

                current_date = datetime.now().strftime("%Y-%m-%dT%H:%M:%S+00:00")

                front_matter = f"""---
title: "{chapter_title}"
date: {current_date}
draft: false
tags: ["tutorial", "guide", "learning"]
categories: ["Learning Guides"]
toc: true
author: "AI Learning Guide Generator"
description: "Learn about {chapter_title}"
weight: {i + 1}
---

# {chapter_title}

*Content will be generated here...*
"""

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(front_matter)

                chapter_files[chapter_title] = str(file_path)

            logger.info(f"Created {len(chapter_files)} chapter files")
            return chapter_files
        except Exception as e:
            logger.error(f"Error creating chapter files: {e}")
            raise

    def save_chapter_content_tool(
        self, file_path: str, content: str, title: str, chapter_index: int = 1
    ) -> str:
        """Save generated content to chapter file with Hugo front matter"""
        try:
            current_date = datetime.now().strftime("%Y-%m-%dT%H:%M:%S+00:00")

            front_matter = f"""---
title: "{title}"
date: {current_date}
draft: false
tags: ["tutorial", "guide", "learning"]
categories: ["Learning Guides"]
toc: true
author: "AI Learning Guide Generator"
description: "Comprehensive guide to {title}"
weight: {chapter_index + 1}
---

"""

            full_content = front_matter + content

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(full_content)

            logger.info(f"Saved content to {file_path}")
            return f"Successfully saved content to {file_path}"
        except Exception as e:
            logger.error(f"Error saving content: {e}")
            raise

    def update_index_tool(
        self, index_path: str, completed_chapter: str, progress: Dict
    ) -> str:
        """Update index file with completion status"""
        try:
            with open(index_path, "r", encoding="utf-8") as f:
                content = f.read()

            completed_count = len(progress.get("completed_chapters", []))
            total_count = progress.get("total_chapters", 0)
            progress_percentage = (
                (completed_count / total_count * 100) if total_count > 0 else 0
            )

            # Add progress indicator
            progress_section = f"""
## ✅ Generation Progress

**Latest Update:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

**Progress:** {completed_count}/{total_count} chapters completed ({progress_percentage:.1f}%)

**Last Completed:** {completed_chapter}

**Status:** {'🎉 Complete!' if completed_count == total_count else '🔄 In Progress...'}

---

"""

            # Insert progress before the final line
            content = content.replace(
                "*Generated by AI Learning Guide Generator",
                progress_section + "*Generated by AI Learning Guide Generator",
            )

            with open(index_path, "w", encoding="utf-8") as f:
                f.write(content)

            logger.info(f"Updated index with progress for {completed_chapter}")
            return f"Updated index with progress for {completed_chapter}"
        except Exception as e:
            logger.error(f"Error updating index: {e}")
            return f"Error updating index: {str(e)}"

    def searxng_search_tool(
        self, query: str, max_results: int = 5
    ) -> List[Dict[str, Any]]:
        """Search using SearxNG for latest information"""
        if not config.search_enabled:
            logger.info("Search is disabled")
            return []

        try:
            params = {
                "q": query,
                "format": "json",
                "safesearch": 0,
                "pageno": 1,
                "engines": "google,duckduckgo,bing",
            }

            response = requests.get(
                f"{config.searxng_url}/search",
                params=params,
                timeout=10,
                headers={"User-Agent": "Learning-Guide-Generator/1.0"},
            )
            response.raise_for_status()

            results = response.json().get("results", [])

            formatted_results = []
            for result in results[:max_results]:
                formatted_results.append(
                    {
                        "title": result.get("title", ""),
                        "url": result.get("url", ""),
                        "snippet": result.get("content", result.get("snippet", "")),
                    }
                )

            logger.info(f"Found {len(formatted_results)} search results")
            return formatted_results

        except requests.exceptions.RequestException as e:
            logger.warning(f"Search request failed: {e}")
            return []
        except Exception as e:
            logger.error(f"Search error: {e}")
            return []

    def generate_content_with_ollama(self, prompt: str, model: str = None) -> str:
        """Generate content using Ollama Mistral model with retries"""
        if model is None:
            model = config.mistral_model

        max_retries = 3
        for attempt in range(max_retries):
            try:
                logger.info(
                    f"Generating content with {model} (attempt {attempt + 1}/{max_retries})"
                )

                response = self.ollama_client.chat(
                    model=model,
                    messages=[{"role": "user", "content": prompt}],
                    options={
                        "temperature": 0.7,
                        "num_ctx": 20000, #8192,  # Increased context window
                        "repeat_penalty": 1.1,
                        "top_k": 40,
                        "top_p": 0.9,
                    },
                )

                content = response["message"]["content"]
                logger.info(
                    f"Successfully generated {len(content)} characters of content"
                )
                return content

            except Exception as e:
                logger.warning(f"Attempt {attempt + 1} failed: {e}")
                if attempt == max_retries - 1:
                    logger.error(f"All attempts failed. Last error: {e}")
                    return f"Error generating content: {str(e)}"

        return "Error: Failed to generate content after multiple attempts"

    def _create_filename(self, title: str) -> str:
        """Create safe filename from title"""
        safe_name = "".join(
            c for c in title if c.isalnum() or c in (" ", "-", "_")
        ).rstrip()
        safe_name = safe_name.replace(" ", "_").lower()[:50]  # Limit length
        return f"{safe_name}.md"

    def parse_query_extract_topic(self, user_query: str) -> str:
        """Extract topic from user query using better parsing"""
        query_lower = user_query.lower()

        # Remove common phrases
        common_phrases = [
            "generate a learning guide for me topic:",
            "generate a learning guide for",
            "create a learning guide for",
            "learning guide for",
            "create a guide for",
            "guide for",
            "tutorial for",
            "learn about",
            "generate guide for",
            "create guide for",
            "make a guide for",
        ]

        topic = user_query.strip()
        for phrase in common_phrases:
            if phrase in query_lower:
                topic = user_query[query_lower.find(phrase) + len(phrase) :].strip()
                break

        # Clean up and capitalize properly
        topic = " ".join(word.capitalize() for word in topic.split() if word.isalnum())

        return topic if topic else "General Programming"

    def generate_topics_structure(self, topic: str, level: str) -> List[Dict[str, Any]]:
        """Generate topic structure based on topic and level with better prompting"""
        #         structure_prompt = f"""
        # You are an expert curriculum designer. Create a comprehensive learning structure for "{topic}" at {level} level.

        # Generate a JSON array of 6-8 chapters, each with:
        # - title: Clear, specific chapter name
        # - subtopics: 3-5 specific subtopics that will be covered

        # Rules:
        # 1. Progress from basic to advanced concepts
        # 2. Each chapter should build upon previous ones
        # 3. Include practical examples and real-world applications
        # 4. Make subtopics specific and actionable

        # Topic: {topic}
        # Level: {level}

        # Return ONLY valid JSON in this exact format:
        # [
        #   {{
        #     "title": "Introduction to {topic}",
        #     "subtopics": ["What is {topic}", "Key Benefits", "Use Cases", "Getting Started"]
        #   }},
        #   {{
        #     "title": "Core Concepts",
        #     "subtopics": ["Fundamental Principles", "Architecture Overview", "Key Components", "Basic Workflow"]
        #   }}
        # ]

        # Generate 6-8 chapters total. Respond with ONLY the JSON array, no explanations.
        # """

        # structure_prompt = f"""
        structure_prompt = f"""
You are an expert curriculum designer and learning pathway architect, utilizing the latest instructional design methodologies for 2025.

Generate a comprehensive learning structure for "{topic}" at {level} level based on modern curriculum development best practices including:
- Learner-centered design principles
- Progressive complexity scaling
- Multi-modal content delivery
- Active learning integration
- Microlearning and content chunking
- Scenario-based learning opportunities

Create a JSON array of 6-8 strategically designed chapters with progressive difficulty, where each chapter includes:
- title: Clear, actionable chapter name that indicates learning outcomes
- subtopics: 4-6 specific, measurable subtopics with progressive complexity
- learning_outcomes: Key skills/knowledge students will gain
- complexity_indicators: Difficulty markers for adaptive learning paths

**Level-Specific Adaptations:**

**If level = "beginner":**
- Focus on foundational concepts and hands-on practice
- Include setup, basic concepts, practical exercises, and guided projects
- Emphasize clear explanations and step-by-step guidance
- Incorporate frequent checkpoints and reinforcement

**If level = "advanced":**  
- Emphasize complex problem-solving, optimization, and expert-level patterns
- Include architecture considerations, performance analysis, and case studies
- Focus on industry best practices and cutting-edge applications
- Incorporate research directions and specialization areas

**If level = "combined":**
- Structure with progressive learning tracks (🟢 Beginner → 🟡 Intermediate → 🔴 Advanced)
- Include multi-level examples and adaptive pathways
- Provide clear skill level indicators and flexible navigation
- Balance foundational knowledge with advanced applications

**Universal Requirements:**
1. Each chapter must build logically upon previous concepts
2. Include practical applications and real-world relevance
3. Incorporate active learning elements (exercises, projects, assessments)
4. Ensure clear learning progression with measurable outcomes
5. Follow modern microlearning principles with digestible content chunks

Topic: {topic}
Level: {level}

Return ONLY valid JSON in this exact format:
[
  {{
    "title": "Getting Started with {topic}: Foundation and Setup",
    "subtopics": [
      "What is {topic} and Why It Matters", 
      "Core Concepts and Terminology", 
      "Development Environment Setup", 
      "First Practical Implementation",
      "Common Pitfalls and Best Practices"
    ],
    "learning_outcomes": [
      "Understand fundamental {topic} concepts",
      "Set up complete development environment", 
      "Create first working implementation"
    ],
    "complexity_indicators": "{level}_friendly"
  }},
  {{
    "title": "Core Principles and Implementation Patterns",
    "subtopics": [
      "Fundamental Architecture and Design",
      "Essential Implementation Techniques", 
      "Code Organization and Structure",
      "Testing and Validation Methods",
      "Performance Considerations"
    ],
    "learning_outcomes": [
      "Master core {topic} implementation patterns",
      "Apply best practices for code organization",
      "Implement comprehensive testing strategies"
    ],
    "complexity_indicators": "building_complexity"
  }}
]

Generate 6-8 chapters total following this enhanced structure. Respond with ONLY the JSON array, no explanations or additional text.
"""
        structure_prompt = structure_prompt_template.format(topic=topic, level=level)

        try:
            logger.info(f"Generating topic structure for {topic} at {level} level")
            response = self.generate_content_with_ollama(structure_prompt)

            # Try to extract JSON from response
            json_start = response.find("[")
            json_end = response.rfind("]") + 1

            if json_start != -1 and json_end > json_start:
                json_str = response[json_start:json_end]
                structure = json.loads(json_str)
                logger.info(
                    f"Successfully generated structure with {len(structure)} chapters"
                )
                return structure
            else:
                logger.warning("Could not parse JSON from response, using fallback")

        except json.JSONDecodeError as e:
            logger.warning(f"JSON parsing error: {e}, using fallback structure")
        except Exception as e:
            logger.error(f"Error generating structure: {e}")

        # Fallback structure
        return self._get_fallback_structure(topic, level)

    def _get_fallback_structure(self, topic: str, level: str) -> List[Dict[str, Any]]:
        """Enhanced fallback topic structure"""
        base_structure = [
            {
                "title": f"Introduction to {topic}",
                "subtopics": [
                    "Overview and History",
                    "Key Concepts",
                    "Benefits and Use Cases",
                    "Getting Started",
                ],
            },
            {
                "title": "Setting Up Your Environment",
                "subtopics": [
                    "Installation Guide",
                    "Configuration",
                    "Development Tools",
                    "First Setup",
                ],
            },
            {
                "title": "Fundamental Concepts",
                "subtopics": [
                    "Core Principles",
                    "Architecture Overview",
                    "Key Components",
                    "Basic Workflow",
                ],
            },
            {
                "title": "Hands-On Practice",
                "subtopics": [
                    "Basic Examples",
                    "Step-by-Step Tutorials",
                    "Common Patterns",
                    "Code Walkthrough",
                ],
            },
            {
                "title": "Intermediate Topics",
                "subtopics": [
                    "Advanced Features",
                    "Best Practices",
                    "Optimization Techniques",
                    "Error Handling",
                ],
            },
            {
                "title": "Real-World Applications",
                "subtopics": [
                    "Project Planning",
                    "Implementation Strategies",
                    "Case Studies",
                    "Production Considerations",
                ],
            },
        ]

        if level == "advanced":
            base_structure.extend(
                [
                    {
                        "title": "Advanced Techniques",
                        "subtopics": [
                            "Performance Optimization",
                            "Scaling Strategies",
                            "Advanced Patterns",
                            "Expert Tips",
                        ],
                    },
                    {
                        "title": "Production Deployment",
                        "subtopics": [
                            "Deployment Strategies",
                            "Monitoring",
                            "Maintenance",
                            "Troubleshooting",
                        ],
                    },
                ]
            )

        return base_structure
